# The name of this app. Must be unique within a project.
name: teamtoolbox

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: 'php:8.2'

# Global dependencies to be added and cached and then available as commands.
dependencies:
  php:
    composer/composer: '^2'

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  'var':
    source: local
    source_path: var
  'data':
    source: local
    source_path: data
  'public/uploads/pictures':
    source: local
    source_path: public/uploads/pictures

# The size of the persistent disk of the application (in MB).
disk: 2048

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"

runtime:
  xdebug:
    idekey: PHPSTORM
  extensions:
    - sqlite3
    - pdo_sqlite
    - pdo_pgsql

hooks:
  build: |
    set -x -e
    
    curl -s https://get.symfony.com/cloud/configurator | bash
    COMPOSER_FLAGS="--ignore-platform-reqs" symfony-build

  deploy: |
    set -e

#relationships:
#  postgresdatabase: "dbpostgres:postgresql"

web:
  locations:
    '/':
      root: "public"
      passthru: "/index.php"

    '/uploads/pictures':
        expires: 300
        passthru: true
        allow: false
        rules:
          # Only allow static image files in this location
          '\.(jpe?g|png|gif|svgz?|ico|bmp)$':
            allow: true